### ISSUE TITLE
Standard Filters

### ISSUE THREAD

**Issue by wraythezw** [TaqsBlaze/ReqWeb#3]
In many commercial WAFs, you have a standardized setting to block connections from
- Bogons
- RFC1918
- Non routable ranges (IANA unallocated)
- Multicast 224.x.x.x
- Broadcast

It would be good to offer this as a config option, which is enabled by default - at least with the bogons and non routable ranges.

**Comment by TaqsBlaze** [comment]
tanks for bringing this up as one of the goals is to bring industry level config that are normally found in commercial versions to this one and offer them all for free
you will find these in the next release
User can already configure blocked and allowed IPs via the new dashboard these are the first options at the top
